---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "XGbN2cE3oAHE2LLu0aK3PFmF4BEg/ciCtP50uXwLdOV+T97GYwG1szMEE1sBYN3joYoPPPCOeZ+KTqqo6aKBiVFCvdTmiOneJ+NzJzYRHnpp86JM0hMl2HM/8MuPq8Mj9cviTC1GNLgTh5UlRervsAXhfkrlSnppVkScyrP1z8LQvIHdix346OVD/Z5rAytE5Pi0cH7E2Wo/ckljVibK1vnaW/mT++CSUUZPilQF7q91GTepJlNs9NM0apMdhwHZsFUPf9v0O8I9p42k2ovuZqjYuYG1nHsdIMcjRduK+YlMhv3kOh2pYgJfbIgYkVJdbPU3+x/gLnuuMnkbQleDEm58vX4GOG6BOAA3gYkaXKy2frJ4TLkN6HwpV9b+zZzUbB9pCPsai4yAg4ML4RYO4pLLsyRBg2KuWCaIXwd1mTMi20suvl/G6gA8FP3WSbHaLxttgdvJNcD00ENiSPP1dUTXd+Q2y71hINdUV6wWj/0HleP6eyA2yz97EGbYx6h/W8tua3ni6VvqaADceGxTghl7fpaH4zdDu2SaRE5F/vws4nsusKYszP8Naodf24EXxNJfU2DUYvpRunJbf0SWBGDvQzejL60cAfHuzpmsBNl9XYF9yggeO6jS7UsPDKp8hTxIDb/S006vC6Us/c1Japxj1p5J/ZMqfX0s2SnHYko="
  email: false
