---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="fedora" tag="31"
    - image="opensuse" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "vxVGaX/bpL9XsfeKRgqMAfxrV3TXyFioklU3xCM2jQtQVzS6IZmLcUahn1WBoR5zNirqF+1tqraABA5dPWkMkBRzG82p+ONPXthtK7DRqwRdXE6o7lDINtfA+MwEnR7oo4x1CmYqBw6+rM6L4Q5FdFva29YjWyWd1kdDqtuPm3wedvTsP6aSB1Gd58Lbs0vtjyo+fqktgvjuBgtGfKB7yVviHeAcgl+tyefK4ix+1EYJv2ZlGVwWWJcu0zXKyluu0tTDHPJhL8bLA4JV3AkHwP3nEHv/GlrW1Id9hU5k1stQiXC5QYMIDlPHjIcFwFZDtoL4PahhelAUGKpELdcS+8BTVrNBdSKmTXu05hMf7ybzNi010ubyFU0qtMpbX54+fXpIof0jgD8UWNshTE+6BFT0ntqfqZE4X38WHGuhTR/HjTdTAKsgSb9MXO/uZSQ7trNKm/kcnpw32zT4tYTXgO7jleiwamOv7zEGjW1yGJ443b9LpXhCJLpAWHygK7TKsuNWEX32zRqfRXEVwMriuVGn3ZrwxpfF2w3gq79NmhkIIBYtJllRyz1cC47Cng+BGWXMmhuZCHBgbaZ1cd0MSZWnh8Wlf6wN/esDLoXkKtYYO6WUt5zl6+KaN+MsVdRxVq12I5EZYiDWr/7IxoLMtAjt1gupmT5peGiG39hzmZg="
  email: false
