---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ owncloud_requirements[ansible_distribution]
          | default(owncloud_requirements['default']) }}"
    state: "{{ owncloud_package_state }}"

- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  with_items:
    - "{{ owncloud_sebooleans }}"

- name: install software
  unarchive:
    src: "{{ owncloud_archive }}"
    dest: "{{ owncloud_destination[ansible_distribution]
          | default(owncloud_destination['default']) }}"
    remote_src: yes
    owner: "{{ owncloud_httpd_owner[ansible_distribution]
           | default(owncloud_httpd_owner['default']) }}"
    group: "{{ owncloud_httpd_group[ansible_distribution]
           | default(owncloud_httpd_group['default']) }}"
    creates: "{{ owncloud_destination[ansible_distribution]
          | default(owncloud_destination['default']) }}/owncloud"

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_config_directory[ansible_distribution]
          | default(owncloud_config_directory['default']) }}/owncloud.conf"
  notify:
    - restart httpd

- name: configure owncloud
  command: "{{ owncloud_command }}"
  args:
    creates: "{{ owncloud_destination[ansible_distribution]
             | default(owncloud_destination['default']) }}/owncloud/config/config.php"
    chdir: "{{ owncloud_destination[ansible_distribution]
           | default(owncloud_destination['default']) }}/owncloud"
  become_user: "{{ owncloud_httpd_owner[ansible_distribution]
               | default(owncloud_httpd_owner['default']) }}"
  become: yes
  when:
    - ansible_virtualization_type != "docker"
  notify:
    - set owncloud trusted domains

- name: set permissions
  file:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ owncloud_permissions }}"

- name: start php-fpm
  service:
    name: "{{ owncloud_fpm_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
