---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ owncloud_requirements }}"
    state: "{{ owncloud_package_state }}"

- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  with_items:
    - "{{ owncloud_sebooleans }}"

- name: install owncloud
  unarchive:
    src: "{{ owncloud_archive }}"
    dest: "{{ owncloud_destination }}"
    remote_src: yes
    owner: "{{ owncloud_httpd_owner }}"
    group: "{{ owncloud_httpd_group }}"
    creates: "{{ owncloud_destination }}/owncloud"

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_config_directory }}/owncloud.conf"
  notify:
    - restart httpd

- name: configure owncloud
  command: "{{ owncloud_command }}"
  args:
    creates: "{{ owncloud_destination }}/owncloud/config/config.php"
    chdir: "{{ owncloud_destination }}/owncloud"
  when:
    - ansible_virtualization_type != "docker"
  notify:
    - set owncloud trusted domains

- name: set permissions
  file:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ owncloud_permissions }}"

- name: place php-fpm configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - restart php-fpm
  with_items:
    - src: php-fpm.conf.j2
      dest: "{{ owncloud_fpm_directory }}/php-fpm.conf"
    - src: www.conf.j2
      dest: "{{ owncloud_fpm_include_directory }}/www.conf"

- name: start php-fpm
  service:
    name: "{{ owncloud_fpm_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
