---
# tasks file for owncloud
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_requirements }}"

- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  with_items:
    - "{{ owncloud_sebooleans }}"

- name: install software
  unarchive:
    src: "{{ owncloud_archive }}"
    dest: "{{ owncloud_destination }}"
    remote_src: yes
    owner: "{{ owncloud_httpd_owner }}"
    group: "{{ owncloud_httpd_group }}"
    creates: "{{ owncloud_destination }}/owncloud"

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_config_directory }}/owncloud.conf"
  notify:
    - restart httpd

- name: configure owncloud
  command: php occ maintenance:install --database "mysql" --database-name "{{ owncloud_database_name }}" --database-user "{{ owncloud_database_user }}" --database-pass "{{ owncloud_database_pass }}" --database-host "{{ owncloud_database_host }}" --admin-user "{{ owncloud_admin_user }}" --admin-pass "{{ owncloud_admin_pass }}"
  args:
    creates: "{{ owncloud_destination }}/owncloud/config/config.php"
    chdir: "{{ owncloud_destination }}/owncloud"
  become_user: "{{ owncloud_httpd_owner }}"
  become: yes
  when:
    - ansible_virtualization_type != "docker"
  notify:
    - set owncloud trusted domains

- name: set permissions
  file:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ owncloud_permissions }}"

- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
