---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_configuration[ansible_distribution]['requirements'] }}"

- name: add yum repository
  yum_repository:
    name: owncloud
    description: OwnCloud repository
    baseurl: "{{ owncloud_baseurl }}"
    gpgkey: "{{ owncloud_configuration[ansible_distribution]['key'] }}"
    gpgcheck: yes
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: add zypper repository
  get_url:
    url: "{{ owncloud_configuration[ansible_distribution]['repo'] }}"
    dest: /etc/zypp/repos.d/owncloud.repo
  when:
    ansible_pkg_mgr == "zypper"

- name: add rpm key
  rpm_key:
    key: "{{ owncloud_configuration[ansible_distribution]['key'] }}"
  when:
    ansible_pkg_mgr == "zypper"

- name: add apt key
  apt_key:
    url: "{{ owncloud_configuration[ansible_distribution]['key'] }}"
  when:
    - ansible_pkg_mgr == "apt"

- name: add apt repository
  apt_repository:
    repo: "{{ owncloud_configuration[ansible_distribution]['repo'] }}"
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt-get update

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_packages }}"

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_configuration[ansible_distribution]['config_directory'] }}/owncloud.conf"
  notify:
    - restart httpd

- name: configure owncloud
  command: php occ maintenance:install --database "mysql" --database-name "{{ owncloud_database_name }}" --database-user "{{ owncloud_database_user }}" --database-pass "{{ owncloud_database_pass }}" --admin-user "{{ owncloud_database_admin_user }}" --admin-pass "{{ owncloud_database_admin_pass }}"
  args:
    creates: /var/i/dont/know
    chdir: /var/www/html/owncloud
