---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_configuration[ansible_distribution]['requirements'] }}"

- name: add yum repository
  yum_repository:
    name: owncloud
    description: OwnCloud repository
    baseurl: "{{ owncloud_baseurl }}"
    gpgkey: "{{ owncloud_configuration[ansible_distribution]['owncloud_gpgkey'] }}"
    gpgcheck: yes
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: add zypper repository
  zypper_repository:
    description: OwnCloud repository
    repo: "{{ owncloud_configuration[ansible_distribution]['owncloud_repo'] }}"
    auto_import_keys: yes
  when:
    ansible_pkg_mgr == "zypper"

- name: add apt key
  apt_key:
    url: https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key
  when:
    - ansible_pkg_mgr == "apt"

- name: add apt repository
  apt_repository:
    repo: "{{ owncloud_configuration[ansible_distribution]['owncloud_repo'] }}"
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt-get update

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_packages }}"

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_configuration[ansible_distribution]['config_directory'] }}/owncloud.conf"
  notify:
    - restart httpd
