---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_requirements[ansible_distribution]
      | default(owncloud_requirements['default'] ) }}"

- name: add yum repository
  yum_repository:
    name: owncloud
    description: OwnCloud YUM repository
    baseurl: "{{ owncloud_baseurl }}"
    gpgkey: "{{ owncloud_gpgkey }}"
    gpgcheck: yes
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: add apt repository
  apt_repository:
    repo: "{{ owncloud_repo }}"
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt-get update

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_packages }}"
