---
# tasks file for owncloud
- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ owncloud_configuration[ansible_distribution]['requirements'] }}"

- name: install software
  unarchive:
    src: "{{ owncloud_archive }}"
    dest: "{{ owncloud_configuration[ansible_distribution]['destination'] }}"
    remote_src: yes

- name: place owncloud.conf
  template:
    src: owncloud.conf.j2
    dest: "{{ owncloud_configuration[ansible_distribution]['config_directory'] }}/owncloud.conf"
  notify:
    - restart httpd

- name: configure owncloud
  command: php occ maintenance:install --database "mysql" --database-name "{{ owncloud_database_name }}" --database-user "{{ owncloud_database_user }}" --database-pass "{{ owncloud_database_pass }}" --admin-user "{{ owncloud_database_admin_user }}" --admin-pass "{{ owncloud_database_admin_pass }}"
  args:
    creates: /var/i/dont/know
    chdir: /var/www/html/owncloud
  when:
    - ansible_virtualization_type != "docker"
