---
# tasks file for owncloud
- name: add yum repository
  yum_repository:
    name: owncloud
    description: OwnCloud YUM repository
    baseurl: http://download.owncloud.org/download/repositories/production/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/ce:stable.repo
    gpgkey: https://download.owncloud.org/download/repositories/production/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/repodata/repomd.xml.key
    gpgcheck: yes
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: add apt repository
  apt_repository:
    repo: deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt-get update

- name: install software
  package:
    name: owncloud-files
