---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.redis
    - robertdebock.remi
      remi_enabled_repositories:
        - php73
    - robertdebock.php
    - robertdebock.php_fpm
