---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: owncloud-alpine-edge
    image: alpine:edge
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        owncloud_ignore_docker: no
        httpd_ignore_docker: no
        redis_ignore_docker: no
        php_fpm_ignore_docker: no
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
scenario:
  name: alpine-edge
