---
# handlers file for owncloud
- name: set owncloud trusted domains
  lineinfile:
    path: "{{ owncloud_destination }}/owncloud/config/config.php"
    regexp: "    0 => '"
    line: "    0 => '{{ owncloud_domain_url }}'"

- name: remove config.php
  file:
    path: "{{ owncloud_destination }}/owncloud/config/config.php"
    state: absent
