---
# vars file for owncloud
owncloud_archive: "https://download.owncloud.org/community/owncloud-{{ owncloud_version }}.zip"

owncloud_packages:
  - owncloud-files

owncloud_sebooleans:
  - httpd_tmp_exec
  - httpd_unified

owncloud_config_directory: /etc/httpd/conf.d
owncloud_destination: /var/www/html
owncloud_httpd_owner: apache
owncloud_httpd_group: apache
owncloud_requirements:
  - php-fpm
  - php-gd
  - php-intl
  - php-json
  - php-ldap
  - php-mbstring
  - php-mysqlnd
  - php-pecl-apcu
  - php-pecl-redis
  - php-process
  - php-xml
  - php-zip
  - redis

owncloud_permissions:
  - name: "{{ owncloud_destination }}/owncloud/.htaccess"
    group: root
    mode: 0640
