---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: get status.php
      uri:
        url: "https://{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}/owncloud/status.php"
        validate_certs: no
      delegate_to: localhost
      register: owncloud_get_status_php
      until: owncloud_get_status_php is succeeded
      retries: 3
